const translateObj = {
    'en': {
      'photo': 'Photo',
      'video': 'Video',
      'portfolio': 'Portfolio',
      'prices': 'Price',
      'contacts': 'Contacts',
      'title': 'We create content for marketplaces',
      'miscellanea': 'Miscellanea',
      'furniture': 'Furniture',
      'jewelry': 'Jewelry',
      'technics': 'Technics',
      'clothes': 'Clothes',
      'prams': 'Prams',
      'show-all-photos': 'Show more photos',
      'threeD': '3D photo 360°',
      'show-all-videos': 'Show more video',
      'loft-furniture': 'Promotional video - Loft furniture',
      'shelf-installing': 'Video - Unpacking and installing the shelf',
      'stroller-review': 'Promotion video - Baby stroller review',
      'dishwasher-review': 'Promotional video - Dishwasher review',
      'hob-review': 'Promotional 3D video - Hob review',
      'oven-review': 'Promotional video - Oven review',
      'staged-commercial': 'Backstage - Studio staged video filming of a commercial',
      'clinic-promotional': 'Backstage - Shooting a commercial for a dental clinic',
      'starting': 'Starting',
      'maximum': 'Maximum',
      'optimal': 'Optimal',
      'photo-cards': 'Product photo cards',
      'starts-at-60': 'starts at 60 BYN',
      'object-shooting': 'Object shooting',
      'five-photos': '5 photos',
      'studio-rental': 'Studio rental',
      'photo-retouching': 'Photo retouching',
      'adaptation': 'Adaptation to the requirements of the site and marketplaces',
      'order': 'Order',
      'selling-card': 'Selling product card',
      'starts-at-290': 'starts at 290 BYN',
      'photo-360-1': 'Photo 360 degrees - 1pc',
      'selling-infographics': 'Infographics with a selling description - 1pc',
      'video-review-1': 'Video review - 1pc',
      'сomprehensive-card': 'Сomprehensive product card',
      'starts-at-110': 'starts at 110 BYN',
      'service': 'Service',
      'price': 'Price',
      'subject-photography': 'Subject photography',
      'starts-at-12': 'starts at 12 BYN/photo',
      '360-overview': '360° overview',
      'starts-at-45': 'starts at 45 BYN',
      'product-mobile': 'Product mobile video',
      'starts-at-150': 'starts at 150 BYN',
      'video-infographic': 'Video infographic (based on photos)',
      'starts-at-120': 'starts at 120 BYN',
      'promotional-video': 'Promotional video',
      'starts-at-2500': 'starts at 2500 BYN',
      'infographics': 'Infographics',
      'infographics-pc': '25BYN/pc.',
      'infographics-5': 'Infographics (5 pc.)',
      'additional-services': 'Additional services',
      'stylist-services': 'Stylist services',
      'price-negotiable': 'price is negotiable',
      'delivery': 'delivery to the studio',
      'style-development': 'Development of the style of product cards (content)',
      'style-price': '100BYN (free\xa0starting\xa0at\xa0100\xa0photos)',
      'show-price': 'Show price',
      'hide-price': 'Hide price',
    },
    'ru': {
      'photo': 'Фото',
      'video': 'Видео',
      'portfolio': 'Портфолио',
      'prices': 'Цены',
      'contacts': 'Контакты',
      'title': 'Создаем контент для маркетплейсов',
      'miscellanea': 'Разное',
      'furniture': 'Мебель',
      'jewelry': 'Ювелирка',
      'technics': 'Техника',
      'clothes': 'Одежда',
      'prams': 'Коляски',
      'show-all-photos': 'Показать больше фотографий',
      'threeD': '3D фото 360°',
      'show-all-videos': 'Показать больше видеопроектов',
      'loft-furniture': 'Рекламный видеоролик - Лофт Мебель',
      'shelf-installing': 'Видеоролик - Распаковка и установка полки',
      'stroller-review': 'Рекламный видеоролик - Обзор детской коляски',
      'dishwasher-review': 'Рекламный видеоролик - Обзор посудомоечной машины',
      'hob-review': 'Рекламный видеоролик 3D - Обзор варочной панели',
      'oven-review': 'Рекламный видеоролик - Обзор духового шкафа',
      'staged-commercial': 'Бэкстейдж - Студийная постановочная видеосъемка рекламного ролика',
      'clinic-promotional': 'Бэкстейдж - Видеосъемка рекламного ролика для стоматологической клиники',
      'starting': 'Стартовый',
      'maximum': 'Максимальный',
      'optimal': 'Оптимальный',
      'photo-cards': 'Фотокарточки товаров',
      'starts-at-60': 'от 60 BYN',
      'object-shooting': 'Предметная съёмка',
      'five-photos': '5 фотографий',
      'studio-rental': 'Aренда студии',
      'photo-retouching': 'Ретушь фото',
      'adaptation': 'Адаптация под требования сайта и маркетплейсов',
      'order': 'Order',
      'selling-card': 'Продающая карточка товара',
      'starts-at-290': 'от 290 BYN',
      'photo-360-1': 'Фото 360 градусов - 1шт',
      'selling-infographics': 'Инфографика с продающим описанием - 1шт',
      'video-review-1': 'Видео-обзор - 1шт',
      'сomprehensive-card': 'Полноценная карточка товара',
      'starts-at-110': 'от 110 BYN',
      'service': 'Услуга',
      'price': 'Стоимость',
      'subject-photography': 'Предметная фотосъёмка',
      'starts-at-12': 'от 12BYN/фото',
      '360-overview': 'Обзор 360°',
      'starts-at-45': 'от 45BYN',
      'product-mobile': 'Продуктовый мобильный видеоролик',
      'starts-at-150': 'от 150BYN',
      'video-infographic': 'Видеоинфографика (на основе фотографий)',
      'starts-at-120': 'от 120BYN',
      'promotional-video': 'Рекламный видеоролик',
      'starts-at-2500': 'от 2500BYN',
      'infographics': 'Инфографика',
      'infographics-pc': '25BYN/шт.',
      'infographics-5': 'Инфографика (5шт.)',
      'additional-services': 'Дополнительные услуги',
      'stylist-services': 'Услуги стилиста',
      'price-negotiable': 'цена договорная',
      'delivery': 'Доставка до студии',
      'style-development': 'Разработка стиля карточек товара (контента)',
      'style-price': '100BYN (бесплатно\xa0от\xa0100\xa0фото)',
      'show-price': 'Показать все цены',
      'hide-price': 'Скрыть цены',
    }
  }
  export default translateObj;